filePath: /G:/upload\
fileUrl: http://192.168.1.200:8091/file/
server:
  port: 8081
  servlet:
    context-path: /xhm
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: c3p0, redis, solr
#debug: true