filePath: /D:\Tomcat 7.0\webapps\
fileUrl: http://localhost:8080/
server:
  port: 8082
  servlet:
    context-path: /xhm
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: c3p0, redis, solr


#debug: true