filePath: /E:\Tomcat 8.0\webapps\
fileUrl: http://localhost:8080/
server:
  port: 8081
  servlet:
    context-path: /xhm
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: c3p0, redis, solr
#debug: true